### ISSUE TITLE
Stack smashing / Segmentation fault when using set rxsamplerate/rxbandwidth

### ISSUE THREAD

**Issue by calimeroteknik** [wizardyesterday/RtlSdrDiags#60]
Whenever I send a `set rxsamplerate` or `set rxbandwidth` command, regardless of whether it's before or after starting the receiver or at any point, even to not even change the value (setting the same as is currently set), I get a crash.

```
Entering Data Consumer.
Entering Radio Event Consumer.
Found 1 device(s):
  0:  RTLSDRBlog, Blog V4, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R828D tuner
RTL-SDR Blog V4 Detected
Sampling at 256000 S/s.
Tuner gain set to automatic.
Sampling at 256000 S/s.
*** stack smashing detected ***: terminated
```

Note: my CPU's architecture is x86_64

**Comment by wizardyesterday** [comment]
I believe that your build is corrupt.  O'll jump on IRCon 4 hours after I
finish my hemodialysis session. You are the first that experienced a
segfault since 2017. I wonder if it's  associated with the toolchain you're
using.

**Comment by wizardyesterday** [comment]
This one concerns me. I have to try changing those 2 parameters on my
setup. In the past, I was using an osmocom library release from 2017. Maybe
something became broken in the newer libs. I'll have to regression test the
lib code. I do cut the devs some slack since thr do this stuff on a
volunteer basis.

Kind regards,
Chris G.

**Comment by wizardyesterday** [comment]
Also, could you let me know what values you set for which you set the
sample rate and bandwidth to, in order to cause the segfault?

I want to duplicate the problem on my setup.

Kind regards,
Chris G.

**Comment by wizardyesterday** [comment]
I cannot replicate this problem ony system.

**Comment by calimeroteknik** [comment]
From IRC, I think you have found the issue:
>sscanf(bufferPtr,"%lu",&sampleRate)
>sampleRate is uint32_t

Well there's your problem! Type mismatch, `%lu` is for `long unsigned` as the initials indicate, and `uint32_t` ≠ `long unsigned`. Specifically, on your system they coincide, probably, but on most of the computers in the world now, they don't, `long unsigned` is 64 bits wide.

There are many solutions, pick the one you like best:
- declaring `sampleRate` as `long unsigned`,
- using idiomatic C++ iostream to read into your uint32 (scanf isn't idiomatic C++, it's from C's stdio.h),
- using the PRIu32 macro from C99's inttypes.h,

there are maybe others that don't occur to me immediately.

**Comment by wizardyesterday** [comment]
Thanks! I chose option 1

**Comment by wizardyesterday** [comment]
This fix has been validated by CalimeroTeknik.
