### ISSUE TITLE
Typo/braino in README.txt: set frequency instead of rxfrequency

### ISSUE THREAD

**Issue by calimeroteknik** [wizardyesterday/RtlSdrDiags#63]
I was initially trying to use `set frequency` as indicated in the README.txt, but as it didn't work, I tried `help` and figured it was `set rxfrequency`. Maybe fix the README?

**Comment by wizardyesterday** [comment]
Thanks! I'll fix that tomorrow. :)

So you built and ran my rtlsdr diags?

Kind regards,
Chris G.

**Comment by wizardyesterday** [comment]
Fixed.
